### PR TITLE
feat(pkg): updgrade styleguide

### PR DESCRIPTION
**Pull request by cdaringe**
# problem statement

- @eddier had struggled with getting child component properties propagated to the styleguide.  the new version is much better about parsing all react components found, using `propTypes` and/or `JSDoc` to annotate components.

# solution

- upgrade styleguide

# discussion

- styleguide also got _much better_ about how we render examples.  we can make them more interactive now, too, which is great!  we have a ways to go, but this is seemingly a more and more capable tool.
  - because of this, **i updated most of our example files** to use traditional markdown code blocks to render the examples.
  - you will note for code blocks that you actually want to _just render code in, verses example_, you annotate by doing:

```
\```js static
// rendered as a traditional markdown code block
var a = 'b'
\```

\```js
// renders an styleguide example
<Button />
\```
```

- **BREAKING CHANGE**: imports of components native to octagon are now
imported fromy "react-octagon/components/native/<name>" versus
"react-octagon/components/<name>".  this is to disambiguate between
components authored in library, and those authored from
semantic-ui-react.
  - we can workshop the term `native`, if desired.  i realize that could be non-ideal

### CODE REVIEW

**Comment by wa11-e** [comment]
Woohoo! new surge deployment available for viewing! :tada: [surgereview29770886.surge.sh](http://surgereview29770886.surge.sh)

**Comment by wa11-e** [comment]
Woohoo! new surge deployment available for viewing! :tada: [surgereview29855879.surge.sh](http://surgereview29855879.surge.sh)

**Comment by wa11-e** [comment]
Woohoo! new surge deployment available for viewing! :tada: [surgereview29857290.surge.sh](http://surgereview29857290.surge.sh)

**Comment by wa11-e** [comment]
Woohoo! new surge deployment available for viewing! :tada: [surgereview29857441.surge.sh](http://surgereview29857441.surge.sh)

**Comment by andrewleyva** [comment]
Looks good to me. @cdaringe I updated the ThinCard.examples.md and then updated apostrophes in the file to use the HTML entity.

**Comment by cdaringe** [comment]
ohh i never squash and merge!  it you do, you loose valuable semantic release commit messages!!

**Pull request merged**
