### PR TITLE
Feat/send static site from circle

### PR DESCRIPTION
**Pull request by cdaringe**
# problem statement

- we used to use codeship, now we use circleci, therefore:
  - we dont get updates from @wa11-e w/ static site copies on PR commits
  - we dont cut releases automatically via semantic release

# solution

- complete the transition to circleci

# notes

- circleci gives us the docker-engine fo' free!  codeship didnt.
- you should have access to the circleci builds by simply being a member of the tripwire organization on github.  make sure you log on to circle w/ you public github handle, if it prompts you

### CODE REVIEW

**Comment by andrewleyva** [comment]
Cool. 👍

**Comment by cdaringe** [comment]
looks like @wa11-e didn't post per expectation.  i think i resolved it, but hold off until we get a message back from him here.

**Comment by wa11-e** [comment]
Woohoo! new surge deployment available for viewing! :tada: [undefined](http://surgereviewnegamuaumogvqoh.surge.sh)

**Comment by cdaringe** [comment]
nice.  circle let's you SSH into their builds.  i hacked around and found a bad env var.  this next commit should produce a pristine post.  if it does, ready to review formally.  apologies all on the tagging for review, then the silent build failure.

looks like GH doesn't have a way to remove reviewers, otherwise i would have pulled y'all off while i was debugging.

**Comment by wa11-e** [comment]
Woohoo! new surge deployment available for viewing! :tada: [surgereviewobgaubmslmbkfox.surge.sh](http://surgereviewobgaubmslmbkfox.surge.sh)

**Comment by cdaringe** [comment]
@andrewleyva @ggascoigne, seeking re-approval from new commits.

**Pull request merged**
