### PR TITLE
fix(chart): resolve #77 #78 #80

### LINKED ISSUE #77: BarChartToolTip renders off-screen with large y-axis values
If I change the y-axis value for a particular data point in the BarChart, the tooltip is rendered off-screen. For example, in the styleguide open up BarChart, show the code, and then change the y-value for the single `warning` state to 150, then mouseover the yellow/orange warning bar. The tooltip looks like this:

barchart-tooltip-madness

If you increase the y-value to 500, the tooltip is invisible (presumably far off-screen).

Given that the height of the BarChart is fixed (in the demo it's set to 120), I don't think the tooltip placement should be based on the y-value (if that's what is causing the issue).

### PR DESCRIPTION
**Pull request by eddier**
Issues identified in #78 #77 and #80 are a WIP on this PR.

### CODE REVIEW

**Comment by eddier** [comment]
Hey Josh can you check out this branch to see if it addresses the issues you identified?  The fixes may not be exactly what you need but this should be a good start to the conversation.

**Comment by wa11-e** [comment]
Woohoo! new surge deployment available for viewing! :tada: [surgereview24728910.surge.sh](http://surgereview24728910.surge.sh)

**Comment by jhegg** [comment]
Thanks, I will take a look!

**Comment by jhegg** [comment]
This looks awesome!

**Pull request merged**
