### PR TITLE
feat(theme): Update icon theme to match latest SUI default theme

### LINKED ISSUE #252: SUI theme needs updating for latest font-awesome
There are significant differences between the current default SUI theme for icons and what we have. Some icons appear to just be broken. This is likely due to the apparent upgrade from Font Awesome 4.x to 5.x.

It's not clear to me what we are trying to override for icons in our theme. Can we just get rid of the override? It looks like @andrewleyva added this originally.

### PR DESCRIPTION
**Pull request by youngbob**
# problem statement

The Font Awesome upgrade has broken our theme for some icons. 

# solution

Update to the latest LESS files from the default theme.

Fixes #252

### CODE REVIEW

**Comment by youngbob** [comment]
There are changes to a few snapshots. I haven't attempted to figure out what needs to be "fixed" here yet, this is just for comparison.

**Comment by cdaringe** [comment]
fixed in 053b1790c5d26da1c3bd49ce170cc83500eb641e, 13.1.1

**Comment by cdaringe** [comment]
i apologize, we should have tacked onto your existing work to give you public commit street cred.  forgive this offense

**Comment by youngbob** [comment]
I'll get over it 😄 

Also, you can give someone "credit" without actually basing your commits off of theirs by adding `Co-authored-by` to the commit message:
https://help.github.com/articles/creating-a-commit-with-multiple-authors/

**Pull request closed without merging**
