### PR TITLE
feat(menu): styling for vertical menu

### PR DESCRIPTION
**Pull request by andrewleyva**
# problem statement

The current menu doesn't adhere to the vertical menu styles we want.

# solution

Previous solution was to build a new component, but it seemed better to reuse the existing component. https://github.com/Tripwire/octagon/pull/151
Now we are just restyling the SUIR component and the (developer) user decides if they want to use these styles

### CODE REVIEW

**Comment by wa11-e** [comment]
Woohoo! new surge deployment available for viewing! :tada: [surgereviewfkkwzdcoetncpfo.surge.sh](http://surgereviewfkkwzdcoetncpfo.surge.sh)

**Comment by wa11-e** [comment]
Woohoo! new surge deployment available for viewing! :tada: [surgereviewgrwheixsnvjcyzv.surge.sh](http://surgereviewgrwheixsnvjcyzv.surge.sh)

**Comment by andrewleyva** [comment]
asfasd

**Comment by wa11-e** [comment]
Woohoo! new surge deployment available for viewing! :tada: [surgereviewnwoyoydmmlbemnj.surge.sh](http://surgereviewnwoyoydmmlbemnj.surge.sh)

**Comment by andrewleyva** [comment]
@antoinejuhel This component is no longer under Native Components, it's part of SUIR Menu, and is the second example: 'Vertical Nav Menu'
@cdaringe All changes are styles and this component is namespaced with 'nav':
default: '.ui.vertical.menu'
vertical nav menu: '.ui.vertical.nav.menu'

**Comment by andrewleyva** [comment]
+1 from Yung

**Comment by wa11-e** [comment]
Woohoo! new surge deployment available for viewing! :tada: [surgereviewdedecsegdyvpqfk.surge.sh](http://surgereviewdedecsegdyvpqfk.surge.sh)

**Comment by cdaringe** [comment]
@antoinejuhel, i'll get in the better habit of tagging UX PRs accordingly.

**Comment by antoinejuhel** [comment]
I just got back from travel today. I am conferring with Yung on a small detail and will get back to this later today.

**Comment by antoinejuhel** [comment]
Looks good, 🚢it!

**Comment by andrewleyva** [comment]
Awesome, thanks @antoinejuhel.

**Pull request merged**
