### PR TITLE
chore(commit): Remove test from pre-commit hook

### PR DESCRIPTION
**Pull request by youngbob**
The snapshot tests take a long time to run and nearly always fail. People tend to just skip the pre-commit hooks entirely, which means linting and formatting is also getting skipped.
Remove the test target from the pre-commit hook in the hopes that people will stop skipping the pre-commit hooks. Includes formatting changes from a few files that were clearly skipped before.

### CODE REVIEW

**Comment by andrewleyva** [comment]
Build is breaking right now...
`error https://registry.yarnpkg.com/event-stream/-/event-stream-3.3.6.tgz: Extracting tar content of undefined failed, the file appears to be corrupt: "Unexpected end of data"`

Looks like the fix is either:
a) an update to package.json 
,
  "resolutions": {
    "**/event-stream": "^4.0.1"
  }
b) delete yarn.lock and and run yarn install

https://github.com/eclipse/che/issues/12077

**Comment by youngbob** [comment]
My updated Yarn.lock file from #340 fixes that. I can merge master into this branch to fix.

**Comment by youngbob** [comment]
Back to good ol' snapshot failures.

**Comment by andrewleyva** [comment]
One that is failing has an animation (loader). It's supposed to be hidden from tests I believe (className="hide-in-test" ).

**Comment by youngbob** [comment]
The failures aren't being caused by this PR, though.

**Comment by andrewleyva** [comment]
Yeah. I think they are due to webjerk or snapjerk update.

**Comment by andrewleyva** [comment]
Oh, looks like when Girish created a bunch of examples the snaps didn't get updated. Not sure how the build even happened, it should have broken. 
https://github.com/Tripwire/octagon/pull/323

**Comment by andrewleyva** [comment]
@youngbob Snaps are fixed on master now. It looks like when a bunch of examples got pushed up the accompanying snaps didn't.

**Comment by ggascoigne** [comment]
Woohoo! new surge deployment available for viewing! :tada: [surgereviewlicnlibwrqjihko.surge.sh](http://surgereviewlicnlibwrqjihko.surge.sh)

**Comment by youngbob** [comment]
Well, the build *did* break, just for everything else that tried to build after those changes were merged. There previously wasn't any requirement that the CI build pass or even have an approved PR before merging, but I just fixed that ( #349 ).

**Comment by andrewleyva** [comment]
"I'm not too worried about having them in the pre-commit hook, but I do think that the Ci build should do them and that they should pass as a merge gate in github." - Guy

**Pull request merged**
