### PR TITLE
chore(pkg): kick storybook

### PR DESCRIPTION
**Pull request by cdaringe**
# problem statement

- storybook builds are biffing from the ci service :(
- gh-pages builds are whack

# solution

- ~apply guess n check commits in desperate attempt to recover them.~
- ditch storybook entirely
- have wa11-e run https://github.com/cdaringe/surge-review in CI, publishing styleguidist

### CODE REVIEW

**Comment by cdaringe** [comment]
**[Storybook Hub](https://hub.getstorybook.io/)** is building storybooks for every commit in this PR.

**Latest Storybook: https://400b320e-0290-4512-bcef-82f7d5a0acc8.sbook.io/**
<sub>( Visit [here](https://hub.getstorybook.io/app/github.com/Tripwire/octagon/branch/fix/storybook-builds/) for more info )</sub>

> _This comment is automatically added by Storybook Hub_

**Comment by wa11-e** [comment]
Woohoo! new surge deployment available for viewing! :tada: [surgereview23314237.surge.sh](http://surgereview23314237.surge.sh)

**Comment by wa11-e** [comment]
Woohoo! new surge deployment available for viewing! :tada: [surgereview23314237.surge.sh](http://surgereview23314237.surge.sh)

**Comment by wa11-e** [comment]
Woohoo! new surge deployment available for viewing! :tada: [surgereview23316247.surge.sh](http://surgereview23316247.surge.sh)

**Comment by wa11-e** [comment]
Woohoo! new surge deployment available for viewing! :tada: [surgereview23316897.surge.sh](http://surgereview23316897.surge.sh)

**Comment by wa11-e** [comment]
Woohoo! new surge deployment available for viewing! :tada: [surgereview23316963.surge.sh](http://surgereview23316963.surge.sh)

**Comment by ggascoigne** [comment]
Very nice 👍

**Comment by cdaringe** [comment]
counting guy's +1!

**Pull request merged**
