### PR TITLE
Feature/testing

### PR DESCRIPTION
**Pull request by cdaringe**
# status

- pending resolution of garris/BackstopJS#313

# problem statement

- https://github.com/Tripwire/octagon/issues/17

# solution

- add test framework and baselines

# discussion

phantomjs is the only renderer.  bummer, but possibly good enough for now.  other strategies are moderately more complicated.  we may need to pursue a different strategy, but this is a noble 1st attempt

### CODE REVIEW

**Comment by cdaringe** [comment]
**[Storybook Hub](https://hub.getstorybook.io/)** is building storybooks for every commit in this PR.

**Latest Storybook: https://79512c4c-2fb3-4419-8771-c11acb3fd550.sbook.io/**
<sub>( Visit [here](https://hub.getstorybook.io/app/github.com/Tripwire/octagon/branch/feature/testing/) for more info )</sub>

> _This comment is automatically added by Storybook Hub_

**Comment by cdaringe** [comment]
screen shot 2017-03-08 at 3 07 46 pm

so this is nuts.  the phantom rendering in CI looks notably different than in osx

**Comment by cdaringe** [comment]
https://github.com/garris/BackstopJS/issues/313#issuecomment-285203933

**Comment by wa11-e** [comment]
Woohoo! new surge deployment available for viewing! :tada: [surgereview23814044.surge.sh](http://surgereview23814044.surge.sh)

**Comment by cdaringe** [comment]
this is not repeatable enough.

- phantom isn't rendering well enough system to system
- the flexbox thing

i cant get it to work, and im done fighting it. will consider a saucelabs alternative

**Pull request closed without merging**
