### PR TITLE
Menutabs

### PR DESCRIPTION
**Pull request by eddier**
Support for the styled menu tabs - see example in storybook

### CODE REVIEW

**Comment by cdaringe** [comment]
**[Storybook Hub](https://hub.getstorybook.io/)** is building storybooks for every commit in this PR.

**Latest Storybook: https://adada99c-30eb-4353-8396-4a84ecbee3f1.sbook.io/**
<sub>( Visit [here](https://hub.getstorybook.io/app/github.com/Tripwire/octagon/branch/menutabs/) for more info )</sub>

> _This comment is automatically added by Storybook Hub_

**Comment by cdaringe** [comment]
+1

**Comment by ggascoigne** [comment]
I noticed that the mouse icon when hovering over the menu tabs is the text entry cursor rather than the hand pointer.

**Comment by cdaringe** [comment]
see https://github.com/Tripwire/octagon/issues/26. just adding an xref

**Pull request merged**
