### PR TITLE
Format source with prettier-standard

### PR DESCRIPTION
**Pull request by youngbob**
# problem statement

Some source files have not been correctly formatted with prettier-standard.

# solution

Run `yarn format`

# discussion

This should be happening on every commit, but people have been skipping the pre-commit hook.

The most likely reason for skipping the pre-commit hook is that it runs snapshot tests, which take a long time and will fail if you haven't run a styleguide build and are generally a pain. I think we should get rid of the snaphot test part of the pre-commit hook to encourage people to stop skipping it (which skips the really useful parts of it: linting and formatting).

### CODE REVIEW

**Comment by cdaringe** [comment]
In regard to the comments, sounds good

**Comment by ggascoigne** [comment]
As an aside, we've seen quite a few cases where the pre-commit hooks simply don't run, if husky gets upgraded it often fails to correctly re-install it's pre-commit hook, and you are left with a checkout that silently fails to run any hooks.  Manually deleting the hook and reinstalling husky fixes things.

It might not be people actively avoiding the pre-commit hooks.

**Comment by youngbob** [comment]
A fair point - especially since I just had to fix husky's config in #299 

I still stand by my assertion that running the full snapshot test as a precommit hook is a huge pain (especially since it doesn't rebuild styleguide - see #266 , so it pretty much always fails for me and makes commits take forever). Long-running tests belong in a CI build for a PR - which is already in place for this repo.

**Comment by ggascoigne** [comment]
I completely agree.

**Comment by andrewleyva** [comment]
Yeah, I didn't realize the pre-commit hooks were running. My commit on the PR is a mess because my IDE went wild with tabs and yarn lint didn't run. Did it manually later.

Absolutely support pre-commit hooks, including the possibly controversial snaps.

**Comment by andrewleyva** [comment]
Also, thanks @youngbob for cleaning that up. I ran yarn lint, but not yarn format. I'm going to add both the our Contrib

**Pull request merged**
